Problem/nqueens
corail-research/SeaPearlZoo pull request #3
Opened 2021-05-03 16:32 UTC by tomsander1998

Using the new AllDifferent constraint, this is a proposition for solving the N-Queens problem using the CP solver of SeaPearl. It contains : 

functions that solve/plot/return solutions for the N-queens problem, with additional arguments on the value and variable selection.

Potential improvements are:

-adding Heuristiques well suited for the N-queens problem

2021-05-03 16:56 UTC, PierreTsr requested changes
Don't forget to remove .DS_Store from the PR, and please add `*.DS_Store` at the end of `.gitignore`.
Other remarks are minor and PR could be merged even if they aren't corrected.

2021-05-03 16:56 UTC, PierreTsr commented on classic_cp/N_Queens/N_Queens.jl
> +    end
Matrices are stored by columns in Julia. It might be more coherent to store solutions by columns and not by rows, but this is a minor observation.

2021-05-03 16:56 UTC, PierreTsr commented on classic_cp/N_Queens/N_Queens.jl
> +
It could be useful to overload `solve_queens` with a function taking an existent model.

2021-05-03 18:22 UTC, PierreTsr requested changes
`solve_queens(::CPModel)` would probably fail.

2021-05-03 18:22 UTC, PierreTsr commented on classic_cp/N_Queens/N_Queens.jl
> +
`variableSelection` and `valueSelection` aren't defined in the new `solve_queens`.

2021-05-03 18:38 UTC, PierreTsr approved these changes
Fine for me!

2021-05-04 14:56 UTC, kimriouxparadis reviewed
We should agree on a way to name the functions (either camel case or with _).
Nice model!

2021-05-04 14:56 UTC, kimriouxparadis commented on classic_cp/N_Queens/N_Queens.jl
> +        rows_plus[i] = SeaPearl.IntVarViewOffset(rows[i], i, rows[i].id*"+"*string(i))
I think row_plus and row_minus are the diagonals. 
I would rename the variables, but it is just a suggestion.

2021-05-05 15:05 UTC, merged